# Changes here will be overwritten by Copier
_commit: v1.7.4
_src_path: gh:34j/create-minimal-package
create_minimal_package_installation_ids: '62553233'
github_user: 34j
project_name: revideo-psdtool
setup_github: true
setup_npm: true
